### ISSUE TITLE
Could it be based on window title instead app name only?

### ISSUE THREAD

**Issue by semente** [jcrussell/Arya#4]
For example, in my text editor I have the name of the file on the title bar, so I would track in each files/projects I spend my time.

**Comment by jcrussell** [comment]
This could work but the list might get a bit messy. Most browsers set the window title according to the html title tag so if you were on a page for more than a minute, it would show up as a entry in the list. To mitigate this, it could be designed so that there is a collapsible section under each application name that lists the top N window titles but this would require a bit of work to implement.

This isn't something I'm interested in including at the moment but feel free to fork the repo and give it a try if you'd like.

**Comment by semente** [comment]
Thanks @jcrussell! No worries, I might try implement it some day. :)
